### ISSUE TITLE
Installation Problem Mojave: 10.14.5 Node 12.4

### ISSUE THREAD

**Issue by 360disrupt** [jongear/xpc-connect#13]
Setting the path before install to:
```
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin
npm i xpc-connect
```
also tried it with 
```
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:$PATH
npm i xpc-connect
```

```
> xpc-connection@0.1.4 install /Users/user/Projekte/1-NODEJS/pilot/regressions/node_modules/xpc-connection
> node-gyp rebuild

CXX(target) Release/obj.target/binding/src/XpcConnection.o
    ../src/XpcConnection.cpp:103:41: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
xpcObject = xpc_int64_create(value->IntegerValue());
^
/Users/user/.node-gyp/11.7.0/include/node/v8.h:2570:3: note: 'IntegerValue' has been explicitly marked deprecated here
V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
^
/Users/user/.node-gyp/11.7.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
declarator __attribute__((deprecated(message)))
^
../src/XpcConnection.cpp:113:40: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
Local<Object> valueObject = value->ToObject();
^
/Users/user/.node-gyp/11.7.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
^
/Users/user/.node-gyp/11.7.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
declarator __attribute__((deprecated(message)))
^
../src/XpcConnection.cpp:123:40: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
Local<Object> valueObject = value->ToObject();
^
/Users/user/.node-gyp/11.7.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
^
/Users/user/.node-gyp/11.7.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
declarator __attribute__((deprecated(message)))
^
../src/XpcConnection.cpp:143:89: error: too few arguments to function call, expected 2, have 1
Local<Value> propertyValue = object->GetRealNamedProperty(propertyName->ToString());
~~~~~~~~~~~~~~~~~~~~~~~~~~~~                         ^
/Users/user/.node-gyp/11.7.0/include/node/v8.h:3668:3: note: 'GetRealNamedProperty' declared here
V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
^
/Users/user/.node-gyp/11.7.0/include/node/v8config.h:418:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
^
../src/XpcConnection.cpp:143:79: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
Local<Value> propertyValue = object->GetRealNamedProperty(propertyName->ToString());
^
/Users/user/.node-gyp/11.7.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
^
/Users/user/.node-gyp/11.7.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
declarator __attribute__((deprecated(message)))
^
../src/XpcConnection.cpp:254:12: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
^
../../nan/nan.h:1045:3: note: 'MakeCallback' has been explicitly marked deprecated here
NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
^
../src/XpcConnection.cpp:263:12: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
^
../../nan/nan.h:1045:3: note: 'MakeCallback' has been explicitly marked deprecated here
NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
^
6 warnings and 1 error generated.
    make: *** [Release/obj.target/binding/src/XpcConnection.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/11.7.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Projekte/1-NODEJS/pilot/regressions/node_modules/xpc-connection
gyp ERR! node -v v11.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN linear_regression@1.0.0 No description
npm WARN linear_regression@1.0.0 No repository field.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for bluetooth-hci-socket@0.5.1: wanted {"os":"linux,android,win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

Node version: `12.4` with nvm
macOs Mojave: `10.14.5`
gcc -v
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

```
xcode-select -v :`xcode-select version 2354.`

**Comment by jongear** [comment]
Very interesting. I added a build to travis to test your configuration and it passed.

https://travis-ci.com/jongear/xpc-connect/jobs/209246033

One thing to note, this build does not do the path export that was recommended from the previous maintainers. Do you mind trying this one more time without the path export? I'll remove it from the documentation since I don't use that export nor does the CI server.

Lastly, we did do a v8 api update that hasn't made it to npm yet. I'll do a force version push as well to see if this helps. (The v8 update I'm referring to https://github.com/jongear/xpc-connect/pull/8)

**Comment by jongear** [comment]
Ok, I bumped the npm package to include the v8 api updates. Can you `npm uninstall xpc-connect` then `npm install xpc-connect` to pull down the latest version. 

https://github.com/jongear/xpc-connect/releases/tag/v1.3.0

**Comment by 360disrupt** [comment]
Ok, without the PATH export. I'm not quite sure if I have PAth exports on other occasions e.g. bash profile.

```
nMasterG:muse MasterG$ nvm use 12
Now using node v12.4.0 (npm v6.9.0)
MasterG:muse MasterG$ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I think it works:

```
> xpc-connection@0.1.4 install /Users/user/Projekte/1-NODEJS/pilot/regressions/node_modules/xpc-connection
> node-gyp rebuild

CXX(target) Release/obj.target/binding/src/XpcConnection.o
    ../src/XpcConnection.cpp:26:77: error: too few arguments to function call, single argument 'context' was not specified
target->Set(Nan::New("XpcConnection").ToLocalChecked(), tmpl->GetFunction());
~~~~~~~~~~~~~~~~~ ^
/Users/user/.node-gyp/12.4.0/include/node/v8.h:5947:3: note: 'GetFunction' declared here
V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
^
/Users/user/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
^
../src/XpcConnection.cpp:103:54: error: too few arguments to function call, single argument 'context' was not specified
xpcObject = xpc_int64_create(value->IntegerValue());
~~~~~~~~~~~~~~~~~~~ ^
/Users/user/.node-gyp/12.4.0/include/node/v8.h:2565:3: note: 'IntegerValue' declared here
V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
^
/Users/user/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
^
../src/XpcConnection.cpp:113:40: error: no matching member function for call to 'ToObject'
Local<Object> valueObject = value->ToObject();
~~~~~~~^~~~~~~~
    /Users/user/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
^
/Users/user/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
Local<Object> ToObject(Isolate* isolate) const);
^
../src/XpcConnection.cpp:115:78: error: too few arguments to function call, expected 2, have 1
if (valueObject->HasRealNamedProperty(Nan::New("isUuid").ToLocalChecked())) {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                    ^
    /Users/user/.node-gyp/12.4.0/include/node/v8.h:3656:3: note: 'HasRealNamedProperty' declared here
    V8_WARN_UNUSED_RESULT Maybe<bool> HasRealNamedProperty(Local<Context> context,
    ^
    /Users/user/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
    #define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
    ^
../src/XpcConnection.cpp:123:40: error: no matching member function for call to 'ToObject'
    Local<Object> valueObject = value->ToObject();
    ~~~~~~~^~~~~~~~
        /Users/user/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
    V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
    ^
    /Users/user/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
    Local<Object> ToObject(Isolate* isolate) const);
^
../src/XpcConnection.cpp:135:40: error: no matching member function for call to 'GetPropertyNames'
    Local<Array> propertyNames = object->GetPropertyNames();
    ~~~~~~~~^~~~~~~~~~~~~~~~
        /Users/user/.node-gyp/12.4.0/include/node/v8.h:3522:43: note: candidate function not viable: requires single argument 'context', but no arguments were provided
    V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetPropertyNames(
    ^
    /Users/user/.node-gyp/12.4.0/include/node/v8.h:3524:43: note: candidate function not viable: requires at least 4 arguments, but 0 were provided
    V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetPropertyNames(
    ^
../src/XpcConnection.cpp:138:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<Value> propertyName = propertyNames->Get(i);
^
    /Users/user/.node-gyp/12.4.0/include/node/v8.h:3416:3: note: 'Get' has been explicitly marked deprecated here
    V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
^
    /Users/user/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
    declarator __attribute__((deprecated(message)))
    ^
../src/XpcConnection.cpp:143:79: error: no matching member function for call to 'ToString'
    Local<Value> propertyValue = object->GetRealNamedProperty(propertyName->ToString());
    ~~~~~~~~~~~~~~^~~~~~~~
        /Users/user/.node-gyp/12.4.0/include/node/v8.h:2528:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
    V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
    ^
    /Users/user/.node-gyp/12.4.0/include/node/v8.h:2544:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
    Local<String> ToString(Isolate* isolate) const);
^
../src/XpcConnection.cpp:160:33: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<Value> value = array->Get(i);
^
    /Users/user/.node-gyp/12.4.0/include/node/v8.h:3416:3: note: 'Get' has been explicitly marked deprecated here
    V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
^
    /Users/user/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
    declarator __attribute__((deprecated(message)))
    ^
../src/XpcConnection.cpp:200:13: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    object->Set(Nan::New<String>(key).ToLocalChecked(), XpcConnection::XpcObjectToValue(value));
^
    /Users/user/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
    V8_DEPRECATE_SOON("Use maybe version",
    ^
    /Users/user/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
    declarator __attribute__((deprecated(message)))
    ^
../src/XpcConnection.cpp:212:12: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    array->Set(Nan::New<Number>(index), XpcConnection::XpcObjectToValue(value));
^
    /Users/user/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
    V8_DEPRECATE_SOON("Use maybe version",
    ^
    /Users/user/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
    declarator __attribute__((deprecated(message)))
    ^
../src/XpcConnection.cpp:254:12: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
^
../../nan/nan.h:1045:3: note: 'MakeCallback' has been explicitly marked deprecated here
    NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
    ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
    ^
../src/XpcConnection.cpp:263:12: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
^
../../nan/nan.h:1045:3: note: 'MakeCallback' has been explicitly marked deprecated here
    NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
    ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
    ^
    6 warnings and 7 errors generated.
        make: *** [Release/obj.target/binding/src/XpcConnection.o] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/Users/user/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
    gyp ERR! System Darwin 18.6.0
    gyp ERR! command "/Users/user/.nvm/versions/node/v12.4.0/bin/node" "/Users/user/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/user/Projekte/1-NODEJS/pilot/regressions/node_modules/xpc-connection
    gyp ERR! node -v v12.4.0
    gyp ERR! node-gyp -v v3.8.0
    gyp ERR! not ok

    > xpc-connect@1.3.1 install /Users/user/Projekte/1-NODEJS/pilot/regressions/node_modules/xpc-connect
    > node-gyp rebuild

    CXX(target) Release/obj.target/xpc-connect/src/XpcConnect.o
        ../src/XpcConnect.cpp:157:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<Value> propertyName = propertyNames->Get(i);
^
    /Users/user/.node-gyp/12.4.0/include/node/v8.h:3416:3: note: 'Get' has been explicitly marked deprecated here
    V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
^
    /Users/user/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
    declarator __attribute__((deprecated(message)))
    ^
../src/XpcConnect.cpp:179:33: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<Value> value = array->Get(i);
^
    /Users/user/.node-gyp/12.4.0/include/node/v8.h:3416:3: note: 'Get' has been explicitly marked deprecated here
    V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
^
    /Users/user/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
    declarator __attribute__((deprecated(message)))
    ^
../src/XpcConnect.cpp:219:13: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    object->Set(Nan::New<String>(key).ToLocalChecked(), XpcConnect::XpcObjectToValue(value));
^
    /Users/user/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
    V8_DEPRECATE_SOON("Use maybe version",
    ^
    /Users/user/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
    declarator __attribute__((deprecated(message)))
    ^
../src/XpcConnect.cpp:231:12: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    array->Set(Nan::New<Number>(index), XpcConnect::XpcObjectToValue(value));
^
    /Users/user/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
    V8_DEPRECATE_SOON("Use maybe version",
    ^
    /Users/user/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
    declarator __attribute__((deprecated(message)))
    ^
    4 warnings generated.
    SOLINK_MODULE(target) Release/xpc-connect.node
    npm WARN linear_regression@1.0.0 No description
    npm WARN linear_regression@1.0.0 No repository field.
        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for bluetooth-hci-socket@0.5.1: wanted {"os":"linux,android,win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 install: `node-gyp rebuild`
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

    + xpc-connect@1.3.1
    updated 1 package and audited 508 packages in 5.479s
    found 3 vulnerabilities (2 low, 1 moderate)
    run `npm audit fix` to fix them, or `npm audit` for details
        MasterG:muse MasterG$ 
```
