### ISSUE TITLE
Can't install with Node v13.14.0

### ISSUE THREAD

**Issue by levyitay** [jongear/xpc-connect#29]
I am running with:
node V13.14
NPM: 6.14.7
MacOS Catalina 
Xcode 12.1
 
```$ npm i xpc-connect
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> xpc-connection@0.1.4 install /Users/itayl/workspace/playground/node_bt_test/node_modules/xpc-connection
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/XpcConnection.o
../src/XpcConnection.cpp:26:77: error: too few arguments to function call, single argument 'context' was not specified
  target->Set(Nan::New("XpcConnection").ToLocalChecked(), tmpl->GetFunction());
                                                          ~~~~~~~~~~~~~~~~~ ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:6283:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/XpcConnection.cpp:103:54: error: too few arguments to function call, single argument 'context' was not specified
    xpcObject = xpc_int64_create(value->IntegerValue());
                                 ~~~~~~~~~~~~~~~~~~~ ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:2774:3: note: 'IntegerValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
  ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/XpcConnection.cpp:113:49: error: too few arguments to function call, single argument 'context' was not specified
    Local<Object> valueObject = value->ToObject();
                                ~~~~~~~~~~~~~~~ ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:2754:3: note: 'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
  ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/XpcConnection.cpp:115:78: error: too few arguments to function call, expected 2, have 1
    if (valueObject->HasRealNamedProperty(Nan::New("isUuid").ToLocalChecked())) {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                    ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3837:3: note: 'HasRealNamedProperty' declared here
  V8_WARN_UNUSED_RESULT Maybe<bool> HasRealNamedProperty(Local<Context> context,
  ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/XpcConnection.cpp:123:49: error: too few arguments to function call, single argument 'context' was not specified
    Local<Object> valueObject = value->ToObject();
                                ~~~~~~~~~~~~~~~ ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:2754:3: note: 'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
  ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/XpcConnection.cpp:135:40: error: no matching member function for call to 'GetPropertyNames'
  Local<Array> propertyNames = object->GetPropertyNames();
                               ~~~~~~~~^~~~~~~~~~~~~~~~
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3702:43: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetPropertyNames(
                                          ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3704:43: note: candidate function not viable: requires at least 4 arguments, but 0 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetPropertyNames(
                                          ^
../src/XpcConnection.cpp:138:48: error: no matching member function for call to 'Get'
    Local<Value> propertyName = propertyNames->Get(i);
                                ~~~~~~~~~~~~~~~^~~
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
../src/XpcConnection.cpp:143:88: error: too few arguments to function call, single argument 'context' was not specified
      Local<Value> propertyValue = object->GetRealNamedProperty(propertyName->ToString());
                                                                ~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:2750:3: note: 'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
  ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/XpcConnection.cpp:160:33: error: no matching member function for call to 'Get'
    Local<Value> value = array->Get(i);
                         ~~~~~~~^~~
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
../src/XpcConnection.cpp:200:13: error: no matching member function for call to 'Set'
    object->Set(Nan::New<String>(key).ToLocalChecked(), XpcConnection::XpcObjectToValue(value));
    ~~~~~~~~^~~
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/XpcConnection.cpp:212:12: error: no matching member function for call to 'Set'
    array->Set(Nan::New<Number>(index), XpcConnection::XpcObjectToValue(value));
    ~~~~~~~^~~
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/itayl/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/XpcConnection.cpp:254:12: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
      Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
           ^
../../nan/nan.h:1047:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/XpcConnection.cpp:263:12: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
      Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
           ^
../../nan/nan.h:1047:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
2 warnings and 11 errors generated.
make: *** [Release/obj.target/binding/src/XpcConnection.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/itayl/workspace/playground/node_bt_test/node_modules/xpc-connection
gyp ERR! node -v v13.14.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> xpc-connect@2.0.0 install /Users/itayl/workspace/playground/node_bt_test/node_modules/xpc-connect
> node-gyp rebuild

  CXX(target) Release/obj.target/xpc-connect/src/XpcConnect.o
  SOLINK_MODULE(target) Release/xpc-connect.node
npm WARN node_bt_test@1.0.0 No description
npm WARN node_bt_test@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for bluetooth-hci-socket@0.5.1: wanted {"os":"linux,android,win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ xpc-connect@2.0.0
added 104 packages from 77 contributors and audited 138 packages in 15.514s

5 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details```

**Comment by jongear** [comment]
thanks for logging this @levyitay, can you try updating to `xpc-connect@2.0.1` :pray:
